table attendance
	lineageTag: 263eb58a-63d6-477d-a1c1-9dd3dbdd72d0

	column attendance_id
		dataType: string
		lineageTag: 6a9596a0-d134-435c-b1d3-7a54cf742279
		summarizeBy: none
		sourceColumn: attendance_id

		annotation SummarizationSetBy = Automatic

	column transaction_id
		dataType: string
		lineageTag: a6f9ac81-a4c4-4b0a-ad97-897a14669564
		summarizeBy: none
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column fan_id
		dataType: string
		lineageTag: bd76b0e1-b0ca-455b-9c56-dafff56b301d
		summarizeBy: none
		sourceColumn: fan_id

		annotation SummarizationSetBy = Automatic

	column game_id
		dataType: string
		lineageTag: b032dac0-49b5-4d2b-84e5-325c1f75d9a8
		summarizeBy: none
		sourceColumn: game_id

		annotation SummarizationSetBy = Automatic

	column tickets_scanned
		dataType: int64
		formatString: 0
		lineageTag: b09ef94e-7fd8-41f0-858a-f7df123fbe9b
		summarizeBy: sum
		sourceColumn: tickets_scanned

		annotation SummarizationSetBy = Automatic

	column scanned_flag
		dataType: int64
		formatString: 0
		lineageTag: faa97730-30f0-44c8-9785-6196be38f564
		summarizeBy: none
		sourceColumn: scanned_flag

		annotation SummarizationSetBy = Automatic

	partition attendance = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\attendance.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"attendance_id", type text}, {"transaction_id", type text}, {"fan_id", type text}, {"game_id", type text}, {"tickets_scanned", Int64.Type}, {"scanned_flag", Int64.Type}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

