table ticket_sales
	lineageTag: fd1422a0-afca-4ea5-a993-d0b7016482b4

	column transaction_id
		dataType: string
		lineageTag: 6c1d0c1f-930f-4820-85ed-5f0fe94c31b2
		summarizeBy: none
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column fan_id
		dataType: string
		lineageTag: a4752545-8887-4169-8b8e-e59756119636
		summarizeBy: none
		sourceColumn: fan_id

		annotation SummarizationSetBy = Automatic

	column game_id
		dataType: string
		lineageTag: bbb29b25-065f-4f8c-8666-be2520ad3ad6
		summarizeBy: none
		sourceColumn: game_id

		annotation SummarizationSetBy = Automatic

	column ticket_type
		dataType: string
		lineageTag: 2f3f97b3-aae4-496e-8cc0-4e88630bc9f3
		summarizeBy: none
		sourceColumn: ticket_type

		annotation SummarizationSetBy = Automatic

	column seat_section
		dataType: string
		lineageTag: 0388dbf8-1f5d-4a10-8e61-ae46ae5aaad4
		summarizeBy: none
		sourceColumn: seat_section

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: b28601db-cf3c-4eb6-8f3a-9a993bb9e2cd
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column ticket_revenue
		dataType: double
		lineageTag: a75fff64-ffd0-4552-89fe-f4677ab24e56
		summarizeBy: sum
		sourceColumn: ticket_revenue

		annotation SummarizationSetBy = Automatic

	column purchase_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 57a902e4-3ac7-4ef6-a2ce-351450e4cced
		summarizeBy: none
		sourceColumn: purchase_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column purchase_channel
		dataType: string
		lineageTag: 819193f3-405a-4de4-a396-cadc073796fb
		summarizeBy: none
		sourceColumn: purchase_channel

		annotation SummarizationSetBy = Automatic

	column campaign_id
		dataType: string
		lineageTag: 8ae66b3e-940b-409d-919d-dec9c5b1e857
		summarizeBy: none
		sourceColumn: campaign_id

		annotation SummarizationSetBy = Automatic

	partition ticket_sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\ticket_sales.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Blanks = Table.ReplaceValue(Headers, "", null, Replacer.ReplaceValue, {"campaign_id"}),
				    Typed = Table.TransformColumnTypes(Blanks, {{"transaction_id", type text}, {"fan_id", type text}, {"game_id", type text}, {"ticket_type", type text}, {"seat_section", type text}, {"quantity", Int64.Type}, {"ticket_revenue", type number}, {"purchase_date", type date}, {"purchase_channel", type text}, {"campaign_id", type text}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

